### ISSUE TITLE
[Question] Config?

### ISSUE THREAD

**Issue by beranPro** [TheSavior/test-pgo-plugin#1]
Hi, 
where can i set my custom configuration (like config.json)?

**Comment by stefansaraev** [comment]
@beranPro put it in your task configuration.
example

```
    "tasks": [
      {
        "type": "test-pgo-plugin.PrintText",
        "config": {
          "test": false
        }
      },
....
```

quick and dirty modified pokemongo_bot/plugins/TheSavior_test-pgo-plugin/test-pgo-plugin/my_print.py example just for this test

```
from pokemongo_bot.base_task import BaseTask

class PrintText(BaseTask):
    SUPPORTED_TASK_API_VERSION = 1

    def initialize(self):
        self.test = self.config.get('test', True)

    def work(self):
        print self.test
        return 'PrintText'
```

**Comment by elicwhite** [comment]
Seems like you got this sorted out. I apparently wasn't watching this repo so I didn't see this until now.
